### ISSUE TITLE
Module Request without Website

### ISSUE THREAD

**Issue by Faraz76** [hilarak/odoo_community_addons#10]
Dear Hilar,

Can you provide this module without dependency of website or just simplify this module for HR data List export to excel file.
Waiting for your response.
Regards,
Faraz

**Comment by Faraz76** [comment]
Thanks Hilarak. I will look forward to see this enhancement.

**Comment by hilarak** [comment]
[hr_dashboard.tar.gz](https://github.com/hilarak/odoo_community_addons/files/2265387/hr_dashboard.tar.gz)
Get the dashboard without the website dependency

**Comment by Faraz76** [comment]
Dear Hilarak,

Thank you for such a useful enhancement. Tonight i will install and check a module and send you my feedback. However, its really excellent work and real professionalism. Well appreciated.

Faraz

**Comment by Faraz76** [comment]
Dear Hilarak,

I have checked the HR Dashboard Modified Module and found below mentioned error. I have tested this module on different 02 OS and different 02 Machines;

Error:
Uncaught TypeError: Cannot read property 'type' of undefined

http://localhost:8069/web/content/600-54f17ba/web.assets_backend.js:478
Traceback:
TypeError: Cannot read property 'type' of undefined
    at Class.get_default_view (http://localhost:8069/web/content/600-54f17ba/web.assets_backend.js:478:432)
    at Class.init (http://localhost:8069/web/content/600-54f17ba/web.assets_backend.js:472:752)
    at Class.prototype.(anonymous function) [as init] (http://localhost:8069/web/content/517-6afaf3e/web.assets_common.js:3816:488)
    at new Class (http://localhost:8069/web/content/517-6afaf3e/web.assets_common.js:3817:65)
    at Object.widget (http://localhost:8069/web/content/600-54f17ba/web.assets_backend.js:451:80)
    at Object.<anonymous> (http://localhost:8069/web/content/600-54f17ba/web.assets_backend.js:449:219)
    at Object.<anonymous> (http://localhost:8069/web/content/517-6afaf3e/web.assets_common.js:802:681)
    at fire (http://localhost:8069/web/content/517-6afaf3e/web.assets_common.js:796:299)
    at Object.add [as done] (http://localhost:8069/web/content/517-6afaf3e/web.assets_common.js:797:467)
    at Array.<anonymous> (http://localhost:8069/web/content/517-6afaf3e/web.assets_common.js:802:649)

Appreciate if you can spare sometime and resolve it.

Regards,
Faraz
