### ISSUE TITLE
HR Dashboard Module without Website

### ISSUE THREAD

**Issue by Faraz76** [hilarak/odoo_community_addons#11]
Dear Hilarak,

I have checked the HR Dashboard Modified Module and found below mentioned error. I have tested this module on different 02 OS and different 02 Machines;

Error:
Uncaught TypeError: Cannot read property 'type' of undefined

http://localhost:8069/web/content/600-54f17ba/web.assets_backend.js:478
Traceback:
TypeError: Cannot read property 'type' of undefined
at Class.get_default_view (http://localhost:8069/web/content/600-54f17ba/web.assets_backend.js:478:432)
at Class.init (http://localhost:8069/web/content/600-54f17ba/web.assets_backend.js:472:752)
at Class.prototype.(anonymous function) [as init] (http://localhost:8069/web/content/517-6afaf3e/web.assets_common.js:3816:488)
at new Class (http://localhost:8069/web/content/517-6afaf3e/web.assets_common.js:3817:65)
at Object.widget (http://localhost:8069/web/content/600-54f17ba/web.assets_backend.js:451:80)
at Object. (http://localhost:8069/web/content/600-54f17ba/web.assets_backend.js:449:219)
at Object. (http://localhost:8069/web/content/517-6afaf3e/web.assets_common.js:802:681)
at fire (http://localhost:8069/web/content/517-6afaf3e/web.assets_common.js:796:299)
at Object.add [as done] (http://localhost:8069/web/content/517-6afaf3e/web.assets_common.js:797:467)
at Array. (http://localhost:8069/web/content/517-6afaf3e/web.assets_common.js:802:649)

Appreciate if you can spare sometime and resolve it.

Regards,
Faraz

**Comment by hilarak** [comment]
I tested the same and I am not experiencing the mentioned problem, Try to restart and reload the server and page.

**Comment by Faraz76** [comment]
Dear Hilarak,

I have tested the module by usig different scnarios; Please see below;

1- Tested on different machines
2- Tested on different OS (Windows 10 and Windows Server 2016)
3- Tested on newly installed OS and also done fresh installation of Odoo 11.
4- Tested with Google Chrome, Firefox and IE
5- Restarted a machines and also restarted a Odoo Server and services.

If the module is working perfect at your end than there must be an issue with the dependent module which i am using. Can you provide me a copy of dependent modules in one RAR file.

Regards,
Faraz

**Comment by Faraz76** [comment]
Hi Hilarak,

Should i expect this module with changes?

Faraz

**Comment by hilarak** [comment]
branch 12 is updated, now without website dependency.

**Comment by Faraz76** [comment]
Dear Hilar,

HR Dashboard Module is throwing below error.

Odoo Client Error


http://localhost:8069/web/content/351-75ce0d5/web.assets_common.js:3374
Traceback:
Error: QWeb2: Template 'hr_dashboard.dashboard' not found
    at Object.exception (http://localhost:8069/web/content/351-75ce0d5/web.assets_common.js:3374:7)
    at Engine._render (http://localhost:8069/web/content/351-75ce0d5/web.assets_common.js:3419:103)
    at Engine.render (http://localhost:8069/web/content/351-75ce0d5/web.assets_common.js:3415:151)
    at Class.render (http://localhost:8069/web/content/362-f9e1899/web.assets_backend.js:3263:1712)
    at Class.prototype.<computed> [as render] (http://localhost:8069/web/content/351-75ce0d5/web.assets_common.js:3538:488)
    at Object.<anonymous> (http://localhost:8069/web/content/362-f9e1899/web.assets_backend.js:3263:1457)
    at fire (http://localhost:8069/web/content/351-75ce0d5/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (http://localhost:8069/web/content/351-75ce0d5/web.assets_common.js:801:198)
    at Object.<anonymous> (http://localhost:8069/web/content/351-75ce0d5/web.assets_common.js:802:874)
    at fire (http://localhost:8069/web/content/351-75ce0d5/web.assets_common.js:796:299)

**Comment by hilarak** [comment]
That's because the contents are property get loaded, A proper server
restart will solves your problem and also do hard refresh the windo.
