### ISSUE TITLE
Failed install via Odoo .zip App menu install

### ISSUE THREAD

**Issue by Industruino** [hilarak/odoo_community_addons#22]
1. When installing the Debrand Odoo module via the Odoo 12 .zip upload method in the Apps menu, the module fails to install correctly. After install the "General Settings" menu will not load, throwing following error:

> Error:
Odoo Server Error
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190218-py3.7.egg/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190218-py3.7.egg/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190218-py3.7.egg/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190218-py3.7.egg/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190218-py3.7.egg/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190218-py3.7.egg/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190218-py3.7.egg/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190218-py3.7.egg/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190218-py3.7.egg/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190218-py3.7.egg/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190218-py3.7.egg/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190218-py3.7.egg/odoo/api.py", line 745, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190218-py3.7.egg/odoo/api.py", line 718, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190218-py3.7.egg/odoo/models.py", line 1376, in load_views
    for [v_id, v_type] in views
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190218-py3.7.egg/odoo/models.py", line 1376, in <dictcomp>
    for [v_id, v_type] in views
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190218-py3.7.egg/odoo/addons/base/models/res_config.py", line 395, in fields_view_get
    toolbar=toolbar, submenu=submenu)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190218-py3.7.egg/odoo/models.py", line 1462, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190218-py3.7.egg/odoo/addons/base/models/ir_ui_view.py", line 1095, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190218-py3.7.egg/odoo/addons/base/models/ir_ui_view.py", line 548, in raise_view_error
    raise ValueError(message)
ValueError: Field `company_logo` does not exist
Error context:
View `n/a`
[view_id: n/a, xml_id: n/a, model: n/a, parent_id: n/a]

2. After a manual install of the module, the module works and access to the "General Settings" menu is restored.

3. When uninstalling the module through the Apps menu, the "General Settings" menu is broken again, with same error.

Is it possible to do a clean uninstall? 

Thank you in advance.

Kind Regards,
Loic

**Comment by hilarak** [comment]
you should try update base @Industruino

**Comment by Industruino** [comment]
@hilarak I tried your suggestion but unfortunately there is no change.
