### ISSUE TITLE
Server code error when clicking General Settings after installing third party module

### ISSUE THREAD

**Issue by M65D85** [hilarak/odoo_community_addons#26]
Hi Hilar,

  Firstly, I would like to thank you for giving this awesome module to us! I tried to get it working but unfortunately I am facing some complication after installing it. Could you please help me out with this issue as I cant seem to wrap my head around it

Basically, after installing the app by importing the module, I am unable to access the General Settings tab. When I click it, a server error code appears. I then proceeded to uninstall the app but the error still persists.

The error code is as follows:

`Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 745, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 718, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1376, in load_views
    for [v_id, v_type] in views
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1376, in <dictcomp>
    for [v_id, v_type] in views
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_config.py", line 395, in fields_view_get
    toolbar=toolbar, submenu=submenu)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1462, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1096, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 548, in raise_view_error
    raise ValueError(message)
ValueError: Field `company_logo` does not exist

Error context:
View `n/a`
[view_id: n/a, xml_id: n/a, model: n/a, parent_id: n/a]`

Appreciate your help on this!

Thanks a lot!!

**Comment by hilarak** [comment]
please check there is a field named company logo in my module. or uprade to latest and reinstall after restarting server

**Comment by M65D85** [comment]
Thank you! 

Also, I had posted a question here that is for you, but i dont have enough points to reply. So would you be so kind to please reply to that issue of mine?

https://www.odoo.com/forum/help-1/question/in-emails-received-how-to-take-off-odoo-branding-116217

Really appreciate it

**Comment by hilarak** [comment]
May be you removed promotion from wrong email template. Try to edit the
correct one.

**Comment by M65D85** [comment]
in the mail_data.xml file, I believe all the templates are there. So I actually removes Powered by Odoo copyright from all the template within this xml file. Could it be that there is another xml file other than this one? I did look around for other files but I could not find anything relevant to email templates.

**Comment by hilarak** [comment]
If you are sending a sale order by using a template, then there will be
promotion also as default. That's why I didn't added the removal from email
templates.

**Comment by M65D85** [comment]
so you mean to say  that we cant remove this trademark from the email footer?

**Comment by hilarak** [comment]
No, I am not in work these days, here weekend started. I well check
tomorrow and let you know.

**Comment by M65D85** [comment]
Thanks a lot brother, really appreciate your help :) I will upvote your comment on the odoo forum also for this.

**Comment by hilarak** [comment]
From where you are trying to send email and with which template? @M65D85

**Comment by M65D85** [comment]
Hi Hilar, 

Thanks for the reply!

So I am trying to send email from here -> 
![Capture](https://user-images.githubusercontent.com/34279492/62114153-af46b100-b2d3-11e9-94f9-77fc3f2d4d2c.JPG)

And the template it is using is this -> 
![template](https://user-images.githubusercontent.com/34279492/62114171-b8d01900-b2d3-11e9-9e07-60307d45297c.JPG)

But when i go to the templates settings under technical > email > templates and open up this template, it does not show the template as a whole, it just shows the body of it. 

Like this -> 
![template_edit](https://user-images.githubusercontent.com/34279492/62114368-2a0fcc00-b2d4-11e9-8882-b8b4540a3124.JPG)

**Comment by M65D85** [comment]
btw, can i get your personal email? I want to discuss a possible project with you if you dont mind. Hopefully you will be interested
