### ISSUE TITLE
Error: QWeb2: Template 'hr_dashboard.dashboard' not found

### ISSUE THREAD

**Issue by afeefksd** [hilarak/odoo_community_addons#6]
Installed HR Dashboard. But showing this error when opening the tab
Error:
Uncaught Error: QWeb2: Template 'hr_dashboard.dashboard' not found

http://localhost:8069/web/content/514-5df5a7a/web.assets_common.js:3689
Traceback:
Error: QWeb2: Template 'hr_dashboard.dashboard' not found
    at Object.exception (http://localhost:8069/web/content/514-5df5a7a/web.assets_common.js:3689:7)
    at Engine._render (http://localhost:8069/web/content/514-5df5a7a/web.assets_common.js:3734:103)
    at Engine.render (http://localhost:8069/web/content/514-5df5a7a/web.assets_common.js:3730:151)
    at Class.render (http://localhost:8069/web/content/738-0b3e962/web.assets_backend.js:2642:1653)
    at Class.prototype.(anonymous function) [as render] (http://localhost:8069/web/content/514-5df5a7a/web.assets_common.js:3816:488)
    at Object.<anonymous> (http://localhost:8069/web/content/738-0b3e962/web.assets_backend.js:2642:1398)
    at fire (http://localhost:8069/web/content/514-5df5a7a/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (http://localhost:8069/web/content/514-5df5a7a/web.assets_common.js:801:198)
    at Object.<anonymous> (http://localhost:8069/web/content/514-5df5a7a/web.assets_common.js:802:874)
    at fire (http://localhost:8069/web/content/514-5df5a7a/web.assets_common.js:796:299)

**Comment by hilarak** [comment]
you should restart the server and refresh the window. @afeefksd
