### ISSUE TITLE
HR Dashboard error

### ISSUE THREAD

**Issue by olalavui** [hilarak/odoo_community_addons#8]
I have install : https://apps.odoo.com/apps/modules/11.0/hr_dashboard/

But on HR Dashboard have error: 

http://ip:8069/web/content/280-ccfecc1/web.assets_common.js:3689
Traceback:
Error: QWeb2: Template 'hr_dashboard.dashboard' not found
    at Object.exception (IP:8069/web/content/280-ccfecc1/web.assets_common.js:3689:7)
    at Engine._render (IP:8069/web/content/280-ccfecc1/web.assets_common.js:3734:103)
    at Engine.render (IP:8069/web/content/280-ccfecc1/web.assets_common.js:3730:151)
    at Class.render (IP:8069/web/content/805-af22bbb/web.assets_backend.js:2933:1653)
    at Class.prototype.(anonymous function) [as render] (IP:8069/web/content/280-ccfecc1/web.assets_common.js:3816:488)
    at Object.<anonymous> (IP:8069/web/content/805-af22bbb/web.assets_backend.js:2933:1398)
    at fire (IP:8069/web/content/280-ccfecc1/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (IP:8069/web/content/280-ccfecc1/web.assets_common.js:801:198)
    at Object.<anonymous> (IP:8069/web/content/280-ccfecc1/web.assets_common.js:802:874)
    at fire (IP:8069/web/content/280-ccfecc1/web.assets_common.js:796:299)

Can you help me?

**Comment by hilarak** [comment]
the issue seems like you have not reloaded the web page after install or the dependencies are not met. @olalavui

**Comment by hilarak** [comment]
No response
